### PR TITLE
RankMe fix, added includes

### PR DESCRIPTION
**Pull request by abnerfs**
- Fixed RankMe loading
- Added necessary .inc files to project
- Changed way to get RankMe points, now is getting in forward RankMe_OnPlayerLoaded instead of get in OnClientPostAdminCheck which was bringing always 1000 points for me.

### CODE REVIEW

**Comment by crashzk** [comment]
It worked for me, but some observations:

- Rank will only display if the player has privileges on the server, even leaving the option of flags in the plugin disabled;
- The option to choose which rank to display does not pick up, only the MM Rank works, the same selected Right Arm does not pick;

Thank you for now!

@abnerfs 
@hallucinogenic

**Comment by luis-rei97** [comment]
@abnerfs if you want, you can add me on steam to discuss about it - https://steamcommunity.com/id/HallucinogenicTroll/

And thank you very much for the help, beeing really busy these past couple of weeks.

**Comment by crashzk** [comment]
Update on the plugin, I did the test with the flag cvar blank and it worked, in case you do not need to use the **"0"**, blank works.

Another BUG I noticed, so I believe, is that in my RankME I have the following active option:
```
// Minimal kills for entering the rank
// -
// Default: "0"
// Minimum: "0.000000"
rankme_minimal_kills "20"
```
That is, it will only show the player in rank after it has 20 kill, however the plugin gives the patent to the player even if it does not kill the 20 players.

I think you have to do with the RankME config:
```
// Starting points
// -
// Default: "1000"
// Minimum: "0.000000"
rankme_points_start "750"
```
After all, the MatchMaking Ranks By Points Plugin uses the points to give the patents, if it already starts with points it gives the patent anyway, correct?

@hallucinogenic 
@abnerfs

**Comment by luis-rei97** [comment]
Since RankMe sets points by default to a new player (as you shown with the cvar), it will show the rank icon as well.

Since you said that about the kills, i researched in the RankMe include files, and it's possible to hide it until you reach a certain number of kills, by using this native:

```SourcePawn
 /*********************************************************
 * Get stats of a player on the server
 *
 * @param client	The client index of the player to get the stats
 * @param stats_return	The array that will return the data following the ENUM STATS_NAME;
 * @noreturn		
 *********************************************************/
native void RankMe_GetStats(int client, int[] stats_return) ;
```

Using the enum below:

```SourcePawn
enum STATS_NAMES{
	SCORE,
	KILLS,
	DEATHS,
	ASSISTS,
	SUICIDES,
	TK,
	SHOTS,
	HITS,
	HEADSHOTS,
	CONNECTED,
	ROUNDS_TR,
	ROUNDS_CT,
	C4_PLANTED,
	C4_EXPLODED,
	C4_DEFUSED,
	CT_WIN,
	TR_WIN,
	HOSTAGES_RESCUED,
	VIP_KILLED,
	VIP_ESCAPED,
	VIP_PLAYED,
	MVP,
	DAMAGE,
	MATCH_WIN,
	MATCH_DRAW,
	MATCH_LOSE,
	FB,
	NS,
	NSD
}
```
For GameMe it's possible as well, but with the ZR Rank, maybe I need to specify if it is kills or infections.

**Comment by crashzk** [comment]
Perfect, I'll be testing your @hallucinogenic version.

Regarding the version of @abnerfs, the one he requested to pull, would he have to modify again to be merged correct?

**[EDTI1]**
@hallucinogenic forgot to speak, its version is resetting the players of players in RankME, always back to 1000 points.

@abnerfs had corrected it in his version, according to him:

>Changed way to get RankMe points, now is getting in forward RankMe_OnPlayerLoaded instead of get in OnClientPostAdminCheck which was bringing always 1000 points for me.

Could you check it out too?

**Comment by luis-rei97** [comment]
Weird, to me it wasn't giving 1000 points o.O
Maybe it's because of the version of RankMe that I've used.
I'll push an update in a few minutes.

**[EDIT]** New version in the repo, check if it is working without problems :)

**Comment by crashzk** [comment]
@hallucinogenic tested for some maps, so far no problem.

In my view, problem solved!

**Pull request closed without merging**
